### ISSUE TITLE
Installing chaos dies with "Install is failed!"

### ISSUE THREAD

**Issue by f00stx** [chaos-lang/occultist#1]
Attempted on both MacOS Catalina and Ubuntu 18.04.4.

```Checking for updates...
Occultist is up to date.
Installing the Chaos language to the system
Installation is failed!
```

It also appears to leave an empty git repo in whatever folder you ran it from.

**Comment by mertyildiran** [comment]
@f00stx could you please comment out [#L161](https://github.com/chaos-lang/occultist/blob/09b84d88efb944bccb59a7adb8a3d6ed2d1b064c/occultist.sh#L161) and [#L174](https://github.com/chaos-lang/occultist/blob/09b84d88efb944bccb59a7adb8a3d6ed2d1b064c/occultist.sh#L174) on `/usr/local/bin/occultist` to see the actual error?

It's running `git init` because `git remote show` fails [here](https://github.com/chaos-lang/occultist/blob/09b84d88efb944bccb59a7adb8a3d6ed2d1b064c/occultist.sh#L107-L108) without a Git repository initialized in the current directory.

Maybe we should go to `/tmp` run `git init` and run `rm -rf .git/` afterwards, I don't know... Maybe there is a better solution. The thing that block trying to achieve is retrieving the default remote branch name.

**Comment by f00stx** [comment]
@mertyildiran Thanks for that - I commented out the lines, and promptly figured it out.

In my .gitconfig:
```
[url "git@github.com:"]
        insteadOf = https://github.com/
```

This is because I need to `go get` private repos, and that was one of the methods suggested to compel git to use ssh instead of https. Removing that from the git config works find (I'm guessing there's a more explicit way to force `go get` to use HTTPS).

Ordinarily it'd work fine because my public key is attached to my github account, but installing with `sudo` means my private key doesn't get used, but my `.gitconfig` does 😆 

So, totally not a bug with the installer at all it seems, but still worth a heads-up.

On that note, is it possible to install `chaos` in userspace? Is there any reason it wouldn't work? I'm thinking along the lines of `rbenv`, `nvm` etc.

**Comment by jamesalbert** [comment]
I got this error too on a fresh alpine container. Uncommenting those lines showed:

```
A new version of Occultist is available! Run:

    sudo occultist upgrade occultist
```

Was just following the install guide on the site.

edit: this just leads to an upgrade loop. I upgrade, says that the upgrade was successful, but reports an error at the end:

```
Upgrading occultist...
Occultist is successfully upgraded.
/usr/local/bin/occultist: line 674: syntax error near unexpected token `}'
/usr/local/bin/occultist: line 674: `} is already removed!${NC}"'
```

Not able to determine what the error actually is. The line number always seems to be the last line of the file (even after attempts to solve). But it does seem to update the file because that block of code that reports the initial error gets commented back, so I'm not sure what's going on here 😄 

For clarity, my "attempts to solve" consisted of running the occultist script through [shellcheck](https://www.shellcheck.net/) and fixing the errors it reported.

**Comment by mertyildiran** [comment]
@f00stx it's good to hear that, it works :blush: 

Installation of the Chaos language is just putting a binary to `/usr/local/bin/chaos` and a bunch of C headers to `/usr/local/include/Chaos.h` and `/usr/local/include/chaos/*`. With this way we don't need to update `PATH` and it has minimal impact on the system. `gcc` or `clang` compilers require `Chaos.h` in default include path to compile the [Chaos C extensions](https://chaos-lang.org/docs/16_chaos_c_extensions_development). It's possible to specify a custom path with `-I...` but some Chaos C extension developers might forget to add this option to their compile commands. Also the custom path might change from system to system, so the extension developers - rather than the language's itself - will have to deal with the cross-platform support.

I have inspired from the path of `/usr/bin/python` binary and `/usr/include/python3.6/Python.h` while choosing those installation paths. Ours is `/usr/local/...` because:

> `/usr/local/bin` is for normal user programs not managed by the distribution package manager, e.g. locally compiled packages. You should not install them into `/usr/bin` because future distribution upgrades may modify or delete them without warning. - https://unix.stackexchange.com/a/8658/238277

**Comment by mertyildiran** [comment]
@jamesalbert this is happening because the Bash script's itself is changing after the upgrade. I think we should put an `exit 0` after [this line](https://github.com/chaos-lang/occultist/blob/09b84d88efb944bccb59a7adb8a3d6ed2d1b064c/occultist.sh#L435).

**Comment by naltun** [comment]
Is this an ongoing bug? @mertyildiran We can still add an explicit `exit`. I'll review the code and get that in, including in any other places.

**Comment by mertyildiran** [comment]
> We can still add an explicit `exit`.

@naltun I'm not sure if it's an ongoing bug or not. What do you mean by this?

**Comment by naltun** [comment]
[This](https://github.com/chaos-lang/occultist/blob/09b84d88efb944bccb59a7adb8a3d6ed2d1b064c/occultist.sh#L435) line runs [here](https://github.com/chaos-lang/occultist/blob/09b84d88efb944bccb59a7adb8a3d6ed2d1b064c/occultist.sh#L634) in the code, and `occultist` implicitly exits after. We may want to explicitly `exit` here, and any other places where it makes sense.

I feel like the bug may no longer be around, but it also makes sense to `exit` when it's appropriate. Thoughts?

**Comment by mertyildiran** [comment]
@naltun yes, feel free to add `exit 0` where it makes sense. But I would prefer places in the main procedure rather than the functions when it's possible.
